name: Automatic data update
on: workflow_dispatch
 # schedule:
 #   - cron:  '0 0,6,12 * * *'
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 21.2.x
        cache: npm
    - name: Install
      run: npm install
    - name: Start
      run: npm start
    - name: Push changes
      run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
